name: Fly Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - run: flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  
  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        if: ${{ github.event_name == 'push' }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  tag_notify:
    name: Notify change
    needs: [tag_release]
    runs-on: ubuntu-latest
    steps:
      - name: New release notification
        run: |
          curl -H "Content-Type: application/json" -d '{"details": "New tag released!", "severity": "info" }' ${{ secrets.DISCORD_WEBHOOK }}
        if: success()
      - name: Build failed notification
        run: |
          curl -H "Content-Type: application/json" -d '{"content": "Build failed! Please check the logs."}' ${{ secrets.DISCORD_WEBHOOK }}
        if: failure()
      # - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      # - name: New release notification
      #   uses: rjstone/discord-webhook-notify@v1
      #   if: success()
      #   with: 
      #     severity: info
      #     details: New tag released!
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      # - name: Build failed notification
      #   if: failure()
      #   uses: rjstone/discord-webhook-notify@v1
      #   with:
      #     severity: error
      #     details: Build failed! Please check the logs.
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}