name: Fly Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - run: flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  
  tag_release:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        if: ${{ github.event_name == 'push' }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: 'patch'